function play(){
    //declare an array to store the images  

    //Image library

    var randImg1 = new Array();  //Dice 1       
    randImg1[0] = "dieWhite1.png";
    randImg1[1] = "dieWhite2.png";
    randImg1[2] = "dieWhite3.png";
    randImg1[3] = "dieWhite4.png";
    randImg1[4] = "dieWhite5.png";
    randImg1[5] = "dieWhite6.png";

    var randImg2 = new Array();  //Dice 2
    randImg2[0] = "dieBlack1.jpg";
    randImg2[1] = "dieBlack2.jpg";
    randImg2[2] = "dieBlack3.jpg";
    randImg2[3] = "dieBlack4.jpg";
    randImg2[4] = "dieBlack5.jpg";
    randImg2[5] = "dieBlack6.jpg";
    
    //generate a number and provide to the image to generate randomly and creates the actual numbers for the 

    var num1 = Math.floor(Math.random()*randImg1.length);
    var die1 = num1 + 1;  //Numbers generated for die 1

    var num2 = Math.floor(Math.random()*randImg2.length);
    var die2 = num2 + 1;  //Numbers generated for die 2
    var sum = die1 + die2;

    //rules for game
    
    if (sum == 7 || sum == 11){  //Loose parameter

        document.getElementById("result").innerHTML = "You loose";
        document.getElementById("result").style.borderColor = '#f4f';

    } else if (die1 == die2 && die1%2 == 0){  //Win parameter

        document.getElementById("result").innerHTML = "You win";
        document.getElementById("result").style.borderColor = "#0cf";

    } else {  //Null parameter

        document.getElementById("result").innerHTML = "Null";
        document.getElementById("result").style.borderColor = "#90f";
    }
    
    //return the images generated by a random number

    document.getElementById("dice1").innerHTML = `<img id="dice1" class="dice1" width="100" height="100" src="${randImg1[num1]}" />`;
    document.getElementById("dice2").innerHTML = `<img id="dice1" class="dice2" width="100" height="100" src="${randImg2[num2]}" />`;
}
